version: '0.2.0.{build}'
configuration:
- Release
# new commit
branches:
  only:
    - master
skip_tags: true
assembly_info:
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\GA.Interactor" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\git-analyser" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
after_build:
- dotnet pack "src\GA.Interactor" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet publish "src\git-analyser" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts\git-analyser
test_script:
- dotnet test "test\git-analyser.tests" -c %CONFIGURATION%
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'
